-- MySQL Script generated by MySQL Workbench
-- Sun May 17 09:56:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema invest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invest` DEFAULT CHARACTER SET utf8 ;
USE `invest` ;

-- -----------------------------------------------------
-- Table `invest`.`inv_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`inv_category` ;

CREATE TABLE IF NOT EXISTS `invest`.`inv_category` (
  `id` INT NOT NULL,
  `category_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`symbols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`symbols` ;

CREATE TABLE IF NOT EXISTS `invest`.`symbols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inv_category_id` INT NOT NULL,
  `symbol_nm` CHAR(25) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `official_symbol_ind` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `symbols_1_fk_idx` (`inv_category_id` ASC),
  CONSTRAINT `symbols_1_fk`
    FOREIGN KEY (`inv_category_id`)
    REFERENCES `invest`.`inv_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`quotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`quotes` ;

CREATE TABLE IF NOT EXISTS `invest`.`quotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `symbol_id` INT NOT NULL,
  `price` DECIMAL(14,5) NOT NULL,
  `stock_dt` DATE NOT NULL,
  `created_dt` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `quotes_1_fk_idx` (`symbol_id` ASC),
  CONSTRAINT `quotes_1_fk`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `invest`.`symbols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`broker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`broker` ;

CREATE TABLE IF NOT EXISTS `invest`.`broker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broker_nm` CHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`inv_acct_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`inv_acct_class` ;

CREATE TABLE IF NOT EXISTS `invest`.`inv_acct_class` (
  `id` INT NOT NULL,
  `broker_id` INT NOT NULL,
  `inv_acct_class_nm` VARCHAR(75) NOT NULL,
  `taxable_ind` TINYINT NULL,
  `comments` VARCHAR(75) NULL,
  PRIMARY KEY (`id`),
  INDEX `inv_type_1_fk_idx` (`broker_id` ASC),
  CONSTRAINT `inv_type_1_fk`
    FOREIGN KEY (`broker_id`)
    REFERENCES `invest`.`broker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`investor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`investor` ;

CREATE TABLE IF NOT EXISTS `invest`.`investor` (
  `id` INT NOT NULL,
  `first_nm` CHAR(20) NULL,
  `last_nm` CHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`investments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invest`.`investments` ;

CREATE TABLE IF NOT EXISTS `invest`.`investments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `symbol_id` INT NOT NULL,
  `inv_acct_class_id` INT NOT NULL,
  `investor_id` INT NOT NULL,
  `quantity` DECIMAL(14,5) NOT NULL,
  `price` DECIMAL(14,5) NOT NULL,
  `inv_dt` DATE NOT NULL,
  `created_dt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `investment_2_fk_idx` (`symbol_id` ASC),
  INDEX `investment_3_fk_idx` (`inv_acct_class_id` ASC),
  INDEX `investor_4_fk_idx` (`investor_id` ASC),
  CONSTRAINT `investment_2_fk`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `invest`.`symbols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `investment_3_fk`
    FOREIGN KEY (`inv_acct_class_id`)
    REFERENCES `invest`.`inv_acct_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `investor_4_fk`
    FOREIGN KEY (`investor_id`)
    REFERENCES `invest`.`investor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
